# Generated by Django 2.0.1 on 2018-01-21 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Fazenda', '0003_auto_20180121_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=18, verbose_name='Código do Animal')),
                ('data_cadastro', models.DateField(default=datetime.date.today, verbose_name='Cadastro')),
                ('peso', models.FloatField(blank=True, default=None, null=True)),
                ('idade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sexo', models.CharField(choices=[('m', 'Macho'), ('f', 'Fêmea')], default='m', max_length=1, verbose_name='Sexo')),
                ('descricao', models.CharField(max_length=100, verbose_name='Tipo ou Raça')),
                ('fazenda', models.ManyToManyField(to='Fazenda.Fazenda')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
            },
        ),
    ]
