# Generated by Django 2.0.1 on 2018-01-22 04:34

import Fazenda.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(db_index=True, max_length=18, verbose_name='CNPJ')),
                ('token', models.CharField(db_index=True, default=Fazenda.models.unique_token, max_length=15, verbose_name='Token é gerado automaticamente')),
                ('nome_propriedade', models.CharField(blank=True, help_text='Nome da fazenda', max_length=128, null=True, verbose_name='Nome Fazenda')),
            ],
            options={
                'verbose_name': 'Fazenda',
                'verbose_name_plural': 'Fazendas',
            },
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateField(default=datetime.date.today, verbose_name='Cadastro')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, db_index=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('cnpj', models.CharField(blank=True, db_index=True, max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino')], default='m', max_length=1, verbose_name='Sexo')),
                ('nascimento', models.DateField(blank=True, null=True, verbose_name='Nascimento')),
                ('naturalidade', models.CharField(blank=True, max_length=30, null=True, verbose_name='Naturalidade')),
                ('nacionalidade', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nacionalidade')),
                ('estado_civil', models.CharField(blank=True, choices=[('c', 'Casado'), ('s', 'Solteiro'), ('d', 'Divorciado'), ('v', 'Viúvo')], max_length=1, null=True, verbose_name='Estado Civil')),
                ('profissao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Profissão')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proprietario',
                'verbose_name_plural': 'Proprietarios',
            },
        ),
        migrations.AddField(
            model_name='fazenda',
            name='proprietario',
            field=models.ManyToManyField(blank=True, null=True, to='Fazenda.Proprietario', verbose_name='Proprietários'),
        ),
    ]
