# Generated by Django 2.0.1 on 2018-01-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fazenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fazenda',
            options={'verbose_name': 'Propriedade Imobiliária', 'verbose_name_plural': 'Propriedades Imobiliárias'},
        ),
        migrations.AddField(
            model_name='fazenda',
            name='cnpj',
            field=models.CharField(db_index=True, default=0, max_length=18, verbose_name='CNPJ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fazenda',
            name='nome_propriedade',
            field=models.CharField(blank=True, help_text='Nome da propriedade', max_length=128, null=True, verbose_name='Nome Propriedade'),
        ),
    ]
