# Generated by Django 2.0.1 on 2018-01-21 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fazenda', '0002_auto_20180120_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateField(default=datetime.date.today, verbose_name='Cadastro')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, db_index=True, max_length=14, null=True, verbose_name='CPF')),
                ('cnpj', models.CharField(blank=True, db_index=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino')], default='m', max_length=1, verbose_name='Sexo')),
                ('nascimento', models.DateField(blank=True, null=True, verbose_name='Nascimento')),
                ('naturalidade', models.CharField(blank=True, max_length=30, null=True, verbose_name='Naturalidade')),
                ('nacionalidade', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nacionalidade')),
                ('estado_civil', models.CharField(blank=True, choices=[('c', 'Casado'), ('s', 'Solteiro'), ('d', 'Divorciado'), ('v', 'Viúvo')], max_length=1, null=True, verbose_name='Estado Civil')),
                ('profissao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Profissão')),
            ],
            options={
                'verbose_name': 'Proprietario',
                'verbose_name_plural': 'Proprietarios',
            },
        ),
        migrations.AlterModelOptions(
            name='fazenda',
            options={'verbose_name': 'Fazenda', 'verbose_name_plural': 'Fazendas'},
        ),
        migrations.AlterField(
            model_name='fazenda',
            name='nome_propriedade',
            field=models.CharField(blank=True, help_text='Nome da fazenda', max_length=128, null=True, verbose_name='Nome Fazenda'),
        ),
        migrations.AddField(
            model_name='fazenda',
            name='proprietario',
            field=models.ManyToManyField(blank=True, null=True, to='Fazenda.Proprietario', verbose_name='Proprietários'),
        ),
    ]
